### ISSUE TITLE
Application Exception: Unexpected character encountered while parsing value: S. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by nminaya** [nminaya/grammar-nazi-bot#115]
This is an issue created automatically by GrammarNazi when an exception was captured.

Date (UTC): 02/01/2021 11:19:43

Exception:

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: S. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at GrammarNazi.Core.Clients.YandexSpellerApiClient.CheckText(String text, String language) in /src/GrammarNazi.Core/Clients/YandexSpellerApiClient.cs:line 30
   at GrammarNazi.Core.Services.YandexSpellerApiService.GetCorrections(String text) in /src/GrammarNazi.Core/Services/GrammarServices/YandexSpellerApiService.cs:line 47
   at GrammarNazi.App.HostedServices.TelegramBotHostedService.OnMessageReceived(Object sender, MessageEventArgs messageEvent) in /src/GrammarNazi.App/HostedServices/TelegramBotHostedService.cs:line 129
   at GrammarNazi.App.HostedServices.TelegramBotHostedService.<ExecuteAsync>b__7_0(Object obj, MessageEventArgs eventArgs) in /src/GrammarNazi.App/HostedServices/TelegramBotHostedService.cs:line 83

**Comment by nminaya** [comment]
This issue is similar to #52. We should fix it the same way.
