### ISSUE TITLE
Application Exception: Response status code does not indicate success: 429 (Too Many Requests).

### ISSUE THREAD

**Issue by nminaya** [nminaya/grammar-nazi-bot#116]
This is an issue created automatically by GrammarNazi when an exception was captured.

Date (UTC): 02/02/2021 08:49:47

Exception:

System.Net.Http.HttpRequestException: Response status code does not indicate success: 429 (Too Many Requests).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at GrammarNazi.App.HostedServices.TelegramBotHostedService.OnMessageReceived(Object sender, MessageEventArgs messageEvent) in /src/GrammarNazi.App/HostedServices/TelegramBotHostedService.cs:line 148
   at GrammarNazi.App.HostedServices.TelegramBotHostedService.<ExecuteAsync>b__7_0(Object obj, MessageEventArgs eventArgs) in /src/GrammarNazi.App/HostedServices/TelegramBotHostedService.cs:line 83

Exception caught counter: 15.

**Comment by nminaya** [comment]
This is a Telegram.Bot issue https://github.com/TelegramBots/Telegram.Bot/issues/891

**Comment by nminaya** [comment]
@Jadhielv Yes, but they haven't officially released the fix yet. It's still in alpha https://github.com/TelegramBots/Telegram.Bot/releases

We can close this issue once the last version is available in Nuget, and we update the package.

**Comment by nminaya** [comment]
@Jadhielv Ok 👍. This will need some testing. The new Telegram.Bot version could have some breaking changes.
