### ISSUE TITLE
Application Exception: An error occurred while sending the request.

### ISSUE THREAD

**Issue by nminaya** [nminaya/grammar-nazi-bot#185]
This is an issue created automatically by GrammarNazi when an exception was captured.

Date (UTC): 04/05/2021 22:03:04

Exception:

System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at GrammarNazi.App.HostedServices.TelegramBotHostedService.OnMessageReceived(Object sender, MessageEventArgs messageEvent) in /src/GrammarNazi.App/HostedServices/TelegramBotHostedService.cs:line 135
   at GrammarNazi.App.HostedServices.TelegramBotHostedService.<ExecuteAsync>b__7_0(Object obj, MessageEventArgs eventArgs) in /src/GrammarNazi.App/HostedServices/TelegramBotHostedService.cs:line 83

**Comment by nminaya** [comment]
This exception was thrown in the following line:

https://github.com/nminaya/grammar-nazi-bot/blob/e2be392ea7ff5fd982fc80b8504ab76988f069d0/GrammarNazi.App/HostedServices/TelegramBotHostedService.cs#L134-L135

Could be related to a Telegram.Bot issue or a momentaneous network issue in the server.

I'll close this since it's currently working ok.
