### ISSUE TITLE
Application Exception: Error on Any

### ISSUE THREAD

**Issue by nminaya** [nminaya/grammar-nazi-bot#193]
This is an issue created automatically by GrammarNazi when an exception was captured.

Date (UTC): 04/16/2021 23:03:29

Exception:

System.InvalidOperationException: Error on Any
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 180 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Firebase.Database.Http.HttpClientExtensions.GetObjectCollectionAsync[T](HttpClient client, String requestUri, JsonSerializerSettings jsonSerializerSettings)
   --- End of inner exception stack trace ---
   at GrammarNazi.Core.Repositories.FirebaseRepository`1.ExecuteFirebaseQuery[TResult](Func`1 action, String callerMemberName) in /src/GrammarNazi.Core/Repositories/FirebaseRepository.cs:line 115
   at GrammarNazi.Core.Repositories.FirebaseRepository`1.Any(Expression`1 filter) in /src/GrammarNazi.Core/Repositories/FirebaseRepository.cs:line 45
   at GrammarNazi.Core.Services.TwitterLogService.GetLastTweetId() in /src/GrammarNazi.Core/Services/TwitterLogService.cs:line 26
   at GrammarNazi.App.HostedServices.TwitterBotHostedService.ExecuteAsync(CancellationToken stoppingToken) in /src/GrammarNazi.App/HostedServices/TwitterBotHostedService.cs:line 73

**Comment by nminaya** [comment]
Firebase was down, now seems to be up
