### ISSUE TITLE
Application Exception: A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 35 - An internal exception was caught)

### ISSUE THREAD

**Issue by nminaya** [nminaya/grammar-nazi-bot#225]
This is an issue created automatically by GrammarNazi when an exception was captured.

Date (UTC): 05/16/2021 06:58:09

Exception:

Microsoft.Data.SqlClient.SqlException (0x80131904): A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 35 - An internal exception was caught)
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ReadAsyncCallbackCaptureException(TaskCompletionSource`1 source)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at GrammarNazi.Core.Repositories.EFRepository`1.GetFirst(Expression`1 filter) in /src/GrammarNazi.Core/Repositories/EFRepository.cs:line 49
   at GrammarNazi.App.HostedServices.DiscordBotHostedService.GetChatConfiguration(SocketUserMessage message) in /src/GrammarNazi.App/HostedServices/DiscordBotHostedService.cs:line 189
   at GrammarNazi.App.HostedServices.DiscordBotHostedService.OnMessageReceived(SocketMessage socketMessage) in /src/GrammarNazi.App/HostedServices/DiscordBotHostedService.cs:line 88
   at GrammarNazi.App.HostedServices.DiscordBotHostedService.<ExecuteAsync>b__8_0(SocketMessage eventArgs) in /src/GrammarNazi.App/HostedServices/DiscordBotHostedService.cs:line 75
ClientConnectionId:c0cfee46-d8bf-4472-8194-278a71649e5a

Exception caught counter: 1.

**Comment by nminaya** [comment]
To me seems like this was caused by a temporary network problem with the database. Now it's running ok.
