### ISSUE TITLE
Application Exception: The connection does not support MultipleActiveResultSets.

### ISSUE THREAD

**Issue by nminaya** [nminaya/grammar-nazi-bot#226]
This is an issue created automatically by GrammarNazi when an exception was captured.

Date (UTC): 05/16/2021 06:58:16

Exception:

System.InvalidOperationException: The connection does not support MultipleActiveResultSets.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at GrammarNazi.Core.Repositories.EFRepository`1.GetFirst(Expression`1 filter) in /src/GrammarNazi.Core/Repositories/EFRepository.cs:line 49
   at GrammarNazi.App.HostedServices.DiscordBotHostedService.GetChatConfiguration(SocketUserMessage message) in /src/GrammarNazi.App/HostedServices/DiscordBotHostedService.cs:line 189
   at GrammarNazi.App.HostedServices.DiscordBotHostedService.OnMessageReceived(SocketMessage socketMessage) in /src/GrammarNazi.App/HostedServices/DiscordBotHostedService.cs:line 88
   at GrammarNazi.App.HostedServices.DiscordBotHostedService.<ExecuteAsync>b__8_0(SocketMessage eventArgs) in /src/GrammarNazi.App/HostedServices/DiscordBotHostedService.cs:line 75

Exception caught counter: 2.

**Comment by nminaya** [comment]
I added MultipleActiveResultSets=True to the connection string
