### ISSUE TITLE
Application Exception: Response status code does not indicate success: 500 (Internal Server Error).

### ISSUE THREAD

**Issue by nminaya** [nminaya/grammar-nazi-bot#262]
This is an issue created automatically by GrammarNazi when an exception was captured.

Date (UTC): 06/23/2021 23:22:07

Exception:

System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at GrammarNazi.App.HostedServices.TelegramBotHostedService.OnMessageReceived(Object sender, MessageEventArgs messageEvent, IServiceProvider serviceProvider) in /src/GrammarNazi.App/HostedServices/TelegramBotHostedService.cs:line 144
   at GrammarNazi.App.HostedServices.TelegramBotHostedService.<ExecuteAsync>b__5_0(Object obj, MessageEventArgs eventArgs) in /src/GrammarNazi.App/HostedServices/TelegramBotHostedService.cs:line 74

Exception caught counter: 1.

**Comment by nminaya** [comment]
Interesting, Telegram Bot API returning 500. I'll assume this was something really random that will not happen again.
