### ISSUE TITLE
Application Exception: The server responded with error 500: 500: Internal Server Error

### ISSUE THREAD

**Issue by nminaya** [nminaya/grammar-nazi-bot#310]
This is an issue created automatically by GrammarNazi when an exception was captured.

Date (UTC): 10/29/2021 17:28:28

Exception:

Discord.Net.HttpException: The server responded with error 500: 500: Internal Server Error
   at GrammarNazi.Core.Utilities.PollyExceptionHandlerHelper.HandleExceptionAndRetry[T](Task action, ILogger logger, CancellationToken cancellationToken, Int32 numberOfTimes) in /src/GrammarNazi.Core/Utilities/PollyExceptionHandlerHelper.cs:line 29
   at GrammarNazi.App.HostedServices.DiscordBotHostedService.<>c__DisplayClass8_0.<<ExecuteAsync>b__0>d.MoveNext() in /src/GrammarNazi.App/HostedServices/DiscordBotHostedService.cs:line 81

Exception caught counter: 51.

**Comment by nminaya** [comment]
Discord API down??
