### ISSUE TITLE
Application Exception: Resource temporarily unavailable (api.twitter.com:443)

### ISSUE THREAD

**Issue by nminaya** [nminaya/grammar-nazi-bot#443]
This is an issue created automatically by GrammarNazi when an exception was captured.

Date (UTC): 06/06/2022 08:55:07

Exception:

System.Net.Http.HttpRequestException: Resource temporarily unavailable (api.twitter.com:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Tweetinvi.WebLogic.TwitterClientHandler.SendAsync(ITwitterQuery twitterQuery, HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Tweetinvi.WebLogic.HttpClientWebHelper.GetHttpResponseAsync(ITwitterQuery twitterQuery, ITwitterClientHandler handler)
   at Tweetinvi.WebLogic.WebRequestExecutor.<>c__DisplayClass4_0.<<ExecuteQueryAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Tweetinvi.WebLogic.WebRequestExecutor.ExecuteTwitterQuerySafelyAsync[T](ITwitterRequest request, Func`1 action)
   at Tweetinvi.WebLogic.TwitterRequestHandler.ExecuteQueryAsync(ITwitterRequest request)
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteRequestAsync[T](ITwitterRequest request)
   at Tweetinvi.Client.BaseRequester.ExecuteRequestAsync[T](Func`2 action)
   at Tweetinvi.Client.UsersClient.GetUsersAsync(IGetUsersParameters parameters)
   at Tweetinvi.Core.Iterators.MultiLevelCursorIteratorFactory.<>c__DisplayClass0_0`3.<<Create>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Tweetinvi.Core.Iterators.MultiLevelCursorIterator`3.NextPageAsync()
   at Tweetinvi.Client.UsersClient.GetFollowersAsync(IGetFollowersParameters parameters)
   at GrammarNazi.App.HostedServices.TwitterBotMentionHostedService.ExecuteAsync(CancellationToken stoppingToken) in /src/GrammarNazi.App/HostedServices/Twitter/TwitterBotMentionHostedService.cs:line 135

Exception caught counter: 1.

**Comment by nminaya** [comment]
Twitter API down for a while
