### ISSUE TITLE
Application Exception: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by nminaya** [nminaya/grammar-nazi-bot#51]
This is an issue created automatically by GrammarNazi when an exception was captured.

Date (UTC): 01/07/2021 14:33:44

Exception:

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at GrammarNazi.Core.Clients.LanguageToolApiClient.Check(String text, String languageCode) in /src/GrammarNazi.Core/Clients/LanguageToolApiClient.cs:line 28
   at GrammarNazi.Core.Services.LanguageToolApiService.GetCorrections(String text) in /src/GrammarNazi.Core/Services/GrammarServices/LanguageToolApiService.cs:line 56
   at GrammarNazi.App.HostedServices.TelegramBotHostedService.OnMessageReceived(Object sender, MessageEventArgs messageEvent) in /src/GrammarNazi.App/HostedServices/TelegramBotHostedService.cs:line 106
   at GrammarNazi.App.HostedServices.TelegramBotHostedService.<ExecuteAsync>b__8_0(Object obj, MessageEventArgs eventArgs) in /src/GrammarNazi.App/HostedServices/TelegramBotHostedService.cs:line 72

**Comment by nminaya** [comment]
Looks like LanguageTool API returned an invalid JSON at that time. I'll close this issue but if the problem is still happening, we will need to handle this scenario.
