### ISSUE TITLE
Application Exception: There is insufficient system memory in resource pool 'internal' to run this query.
Error: 596, Severity: 21, State: 1. (Params:). The error is printed in terse mode because there was error during formatting. Tracing, ETW, notifica...

### ISSUE THREAD

**Issue by nminaya** [nminaya/grammar-nazi-bot#534]
This is an issue created automatically by GrammarNazi when an exception was captured.

Date (UTC): 12/10/2022 13:05:31

Exception:

Microsoft.Data.SqlClient.SqlException (0x80131904): There is insufficient system memory in resource pool 'internal' to run this query.
Error: 596, Severity: 21, State: 1. (Params:). The error is printed in terse mode because there was error during formatting. Tracing, ETW, notifications etc are skipped.

A severe error occurred on the current command.  The results, if any, should be discarded.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__208_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at GrammarNazi.Core.Repositories.EFRepository`1.Any(Expression`1 filter) in /src/GrammarNazi.Core/Repositories/EFRepository.cs:line 32
   at GrammarNazi.Core.Services.TwitterMentionLogService.GetLastTweetId() in /src/GrammarNazi.Core/Services/TwitterMentionLogService.cs:line 26
   at GrammarNazi.App.HostedServices.TwitterBotMentionHostedService.ExecuteAsync(CancellationToken stoppingToken) in /src/GrammarNazi.App/HostedServices/Twitter/TwitterBotMentionHostedService.cs:line 152
ClientConnectionId:d63b4bd5-9210-49a0-801f-ad994beb25ad
Error Number:701,State:123,Class:17

Exception caught counter: 1.

**Comment by nminaya** [comment]
I left this issue a couple of weeks open to see if it happens again, but it didn't
